# Generated by Django 5.0.3 on 2024-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='guest_number',
            new_name='guess_number',
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_item',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
